import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";

import ProviderStore from "./redux/ProviderStore";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Inndus Printing Company",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body
  className={`text-[20px] sm:text-[25px] md:text-[26px] lg:text-[28px] font-[Futura] ${geistSans.variable} ${geistMono.variable} antialiased`}
>
      <ProviderStore>
        {children}
      </ProviderStore>
    </body>
  </html>
  );
}
